theme: jekyll-theme-modernist
title: Welcome to the Rat 2 : Electric Boogaloo homepage!<br\>
description: Rat 2 is an in-development mobile rpg featuring turn-based combat. Its' name comes from the original game, "Rat", which featured exclusively rat-based monsters, such as kobolds, shrews, large rats, and so on. 
